export const bookingRules = {
  timeZone: "Africa/Cairo",
  workDays: [0, 1, 2, 3, 4],
  workStart: "10:00",
  workEnd: "18:00",
  slotStepMin: 30,
  bufferMin: 15,
  minNoticeHours: 24,
  maxDaysAhead: 30,
  durations: [15, 30, 60] as const,
  defaultDuration: 30,
} as const;

export type Duration = (typeof bookingRules.durations)[number];

export const bookingCopy = {
  title: "Discovery call with a Billion engineer",
  description: "Tell us what you are building. We will discuss your goals, technical questions, and practical next steps.",
  meetNote: "Google Meet link sent by email",
  durationLabel: "Duration",
  minutesLabel: "minutes",
  timezoneLabel: "Your timezone",
  timezoneHelp: "Dates and times are shown in your selected timezone.",
  calendarLabel: "Choose a day",
  previousMonthLabel: "Previous month",
  nextMonthLabel: "Next month",
  timeLabel: "Choose a time",
  emptyDay: "No times are available on this day. Please choose another day.",
  emptyMonth: "No times are available this month. Please try another month.",
  selectDay: "Choose a day to see available times.",
  loading: "Loading available times...",
  retry: "Try again",
  selectedDayLabel: "Selected day",
  selectedTimeLabel: "Selected time",
  detailsTitle: "Your details",
  nameLabel: "Name",
  emailLabel: "Email",
  noteLabel: "What should we look at?",
  optionalLabel: "Optional",
  websiteLabel: "Website",
  confirmButton: "Confirm booking",
  confirmingButton: "Confirming booking...",
  changeTimeButton: "Choose another time",
  confirmationTitle: "Your call is booked",
  confirmationBody: "Your calendar invitation and Google Meet link will arrive by email. We look forward to speaking with you.",
  confirmationMeetNote: "Meet link sent to your email",
  calendarLinkLabel: "View calendar invitation",
  meetLinkLabel: "Open Google Meet",
  backToHomeLabel: "Back to home",
  errors: {
    slotTaken: "This time was just booked. Please choose another time.",
    validation: "Please check your details and try again.",
    notConfigured: "Booking is temporarily unavailable. Please try again later.",
    generic: "We could not complete your request. Please try again.",
    rateLimited: "Too many requests. Please wait a while and try again.",
  },
} as const;
